// actionTypes.js
export const FETCH_HOTEL_REVIEWS_SUCCESS = "FETCH_HOTEL_REVIEWS_SUCCESS";
export const FETCH_HOTEL_REVIEWS_FAILURE = "FETCH_HOTEL_REVIEWS_FAILURE";
export const SET_HOTEL_REVIEWS_CURRENT_PAGE = "SET_HOTEL_REVIEWS_CURRENT_PAGE";

// actionTypes.js
export const FETCH_FACILITY_HISTORY_SUCCESS = "FETCH_FACILITY_HISTORY_SUCCESS";
export const FETCH_FACILITY_HISTORY_FAILURE = "FETCH_FACILITY_HISTORY_FAILURE";
export const SET_FACILITY_HISTORY_CURRENT_PAGE =
  "SET_FACILITY_HISTORY_CURRENT_PAGE";

export const SET_SELECTED_HOTEL_DATA = "SET_SELECTED_HOTEL_DATA";
export const SET_ERROR = "SET_ERROR";
